# Generated by Django 3.0.5 on 2020-04-03 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telegrambot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='surname',
            field=models.TextField(default=str, verbose_name='Фамилия пользователя'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bonus', models.PositiveIntegerField(verbose_name='Бонусы')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='telegrambot.Profile', verbose_name='Профиль')),
            ],
            options={
                'verbose_name': 'Бонус',
                'verbose_name_plural': 'Бонусы',
            },
        ),
    ]
